# Generated by Django 3.2.15 on 2023-01-21 08:53

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name="Company's Name")),
            ],
        ),
        migrations.CreateModel(
            name='ConnectorLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Connector Name')),
                ('connector_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Connector Type')),
                ('connector_network_type', models.CharField(choices=[('HTTPS', 'Https'), ('TCP/IP', 'Tcpip'), ('GRAPHQL', 'Graphql'), ('SDK', 'Sdk')], default=None, max_length=20, null=True)),
                ('template_order', models.FileField(blank=True, null=True, upload_to='', verbose_name='Template - Order')),
                ('template_inventory', models.FileField(blank=True, null=True, upload_to='', verbose_name='Template - Inventory')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Connector Description')),
                ('base_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Connector Base Url')),
                ('version', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('connector_structure', models.JSONField(blank=True, null=True, verbose_name='Connector Structure')),
            ],
        ),
        migrations.CreateModel(
            name='SW_User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='wmsconnectors.company')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector_config', models.JSONField(blank=True, null=True, verbose_name='Connector Configurations')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wmsconnectors.company')),
                ('connector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wmsconnectors.connectorlibrary')),
            ],
        ),
    ]
